#**Import Data And Library**


In [26]:
# from google.colab import drive
# drive.mount('/content/drive')

In [27]:
!pip install pyvi

In [28]:
import tensorflow as tf
import pandas as pd
import numpy as np
from string import digits
from collections import Counter
from pyvi import ViTokenizer
from gensim.models.word2vec import Word2Vec
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
%matplotlib inline

In [29]:
from tensorflow.keras.layers import GlobalAveragePooling1D, GlobalMaxPooling1D, Conv1D, MaxPooling1D
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Reshape, Embedding , Flatten, Dropout, Dense, BatchNormalization, concatenate, Bidirectional
from tensorflow.keras.layers import LeakyReLU, Multiply, Activation, RepeatVector, Permute
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras import regularizers
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.optimizers.schedules import ExponentialDecay
from tensorflow.keras.callbacks import ReduceLROnPlateau
from transformers import TFBertModel, BertTokenizer

In [30]:
import os

In [31]:
# !cp -r "/content/drive/MyDrive/NLP_Modern" /content

In [32]:
# %cd "/content/NLP_Modern"

In [33]:
data_train = pd.read_csv("E:/Code/BKU/HK3/NLP/data/vlsp_sentiment_train.csv", sep='\t')
data_train.columns =['Class', 'Data']
data_test = pd.read_csv("E:/Code/BKU/HK3/NLP/data/vlsp_sentiment_test.csv", sep='\t')
data_test.columns =['Class', 'Data']

In [34]:
print(data_train.shape)
print(data_test.shape)

(5100, 2)
(1050, 2)



#**Preprocessing**


In [35]:
labels = data_train.iloc[:, 0].values
reviews = data_train.iloc[:, 1].values

In [36]:
encoded_labels = []

for label in labels:
    if label == -1:
        encoded_labels.append([1,0,0])
    elif label == 0:
        encoded_labels.append([0,1,0])
    else:
        encoded_labels.append([0,0,1])

encoded_labels = np.array(encoded_labels)

In [37]:
reviews_processed = []
unlabeled_processed = []
for review in reviews:
    review_cool_one = ''.join([char for char in review if char not in digits])
    reviews_processed.append(review_cool_one)

In [38]:
#Use PyVi for Vietnamese word tokenizer
word_reviews = []
all_words = []
for review in reviews_processed:
    review = ViTokenizer.tokenize(review.lower())
    word_reviews.append(review.split())


In [39]:
EMBEDDING_DIM = 400 
MAX_VOCAB_SIZE = 10000 
MAX_SEQUENCE_LENGTH = 300 

In [40]:
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE, lower=True, char_level=False)
tokenizer.fit_on_texts(word_reviews)
sequences_train = tokenizer.texts_to_sequences(word_reviews)
word_index = tokenizer.word_index

In [41]:
data = pad_sequences(sequences_train, maxlen=MAX_SEQUENCE_LENGTH)
labels = encoded_labels

In [42]:
print('Shape of X train and X validation tensor:',data.shape)
print('Shape of label train and validation tensor:', labels.shape)

Shape of X train and X validation tensor: (5100, 300)
Shape of label train and validation tensor: (5100, 3)


#**Prepare data for test**

In [43]:
labels_test = data_test.iloc[:, 0].values
reviews_test = data_test.iloc[:, 1].values

In [44]:
encoded_labels_test = []

for label_test in labels_test:
    if label_test == -1:
        encoded_labels_test.append([1,0,0])
    elif label_test == 0:
        encoded_labels_test.append([0,1,0])
    else:
        encoded_labels_test.append([0,0,1])

encoded_labels_test = np.array(encoded_labels_test)

In [45]:
reviews_processed_test = []
unlabeled_processed_test = []
for review_test in reviews_test:
    review_cool_one = ''.join([char for char in review_test if char not in digits])
    reviews_processed_test.append(review_cool_one)

In [46]:
#Use PyVi for Vietnamese word tokenizer
word_reviews_test = []
all_words = []
for review_test in reviews_processed_test:
    review_test = ViTokenizer.tokenize(review_test.lower())
    word_reviews_test.append(review_test.split())

In [47]:
sequences_test = tokenizer.texts_to_sequences(word_reviews_test)
data_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)
labels_test = encoded_labels_test

In [48]:
print('Shape of X train and X validation tensor:',data_test.shape)
print('Shape of label train and validation tensor:', labels_test.shape)

Shape of X train and X validation tensor: (1050, 300)
Shape of label train and validation tensor: (1050, 3)


Word Vector

In [49]:
import gensim
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess

from gensim.models.keyedvectors import KeyedVectors

word_vectors = KeyedVectors.load_word2vec_format('vi-model-CBOW.bin', binary=True)


vocabulary_size=min(len(word_index)+1,MAX_VOCAB_SIZE)
embedding_matrix = np.zeros((vocabulary_size, EMBEDDING_DIM))
for word, i in word_index.items():
    if i>=MAX_VOCAB_SIZE:
        continue
    try:
        embedding_vector = word_vectors[word]
        embedding_matrix[i] = embedding_vector
    except KeyError:
        embedding_matrix[i]=np.random.normal(0,np.sqrt(0.25),EMBEDDING_DIM)


del(word_vectors)

from keras.layers import Embedding
embedding_layer = Embedding(vocabulary_size,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            trainable=True)

In [50]:
vocab_size = 10000
sequence_length = data.shape[1]
num_filters = 128 
filter_sizes = [3, 4, 5]
drop = 0.5
inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

**CNN**

In [51]:
# Improved CNN Architecture
conv_0 = Conv1D(num_filters, filter_sizes[0], activation='relu', kernel_regularizer=regularizers.l2(0.001))(embedding)
conv_0 = BatchNormalization()(conv_0)
conv_0 = Dropout(0.3)(conv_0)  # Increased Dropout in Conv layers

conv_1 = Conv1D(num_filters, filter_sizes[1], activation='relu', kernel_regularizer=regularizers.l2(0.001))(embedding)
conv_1 = BatchNormalization()(conv_1)
conv_1 = Dropout(0.3)(conv_1)  # Increased Dropout in Conv layers

conv_2 = Conv1D(num_filters, filter_sizes[2], activation='relu', kernel_regularizer=regularizers.l2(0.001))(embedding)
conv_2 = BatchNormalization()(conv_2)
conv_2 = Dropout(0.3)(conv_2)  # Increased Dropout in Conv layers

maxpool_0 = GlobalMaxPooling1D()(conv_0)
avgpool_0 = GlobalAveragePooling1D()(conv_0)

maxpool_1 = GlobalMaxPooling1D()(conv_1)
avgpool_1 = GlobalAveragePooling1D()(conv_1)

maxpool_2 = GlobalMaxPooling1D()(conv_2)
avgpool_2 = GlobalAveragePooling1D()(conv_2)

# Added another conv layer for more complex feature learning
conv_3 = Conv1D(num_filters, filter_sizes[0], activation='relu', kernel_regularizer=regularizers.l2(0.001))(embedding)
conv_3 = BatchNormalization()(conv_3)
conv_3 = Dropout(0.3)(conv_3)

maxpool_3 = GlobalMaxPooling1D()(conv_3)
avgpool_3 = GlobalAveragePooling1D()(conv_3)

merged_tensor = concatenate([maxpool_0, avgpool_0, maxpool_1, avgpool_1, maxpool_2, avgpool_2, maxpool_3, avgpool_3])
flatten = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.001))(merged_tensor)
dropout = Dropout(0.5)(flatten)
output = Dense(units=3, activation='softmax', kernel_regularizer=regularizers.l2(0.001))(dropout)

modelCNN = Model(inputs, output)

# Smaller learning rate for potentially better results
adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
modelCNN.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

modelCNN.summary()

#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=6, verbose=1)
callbacks_list = [early_stopping]

c:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 300)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding           │ (None, 300, 400)  │  3,167,600 │ input_layer[0][0] │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d (Conv1D)     │ (None, 298, 128)  │    153,728 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_1 (Conv1D)   │ (None, 297, 128)  │    204,928 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_2 (Conv1D)   │ (None, 296, 128)  │    256,128 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_3 (Conv1D)   │ (None, 298, 128)  │    153,728 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 298, 128)  │        512 │ conv1d[0][0]      │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 297, 128)  │        512 │ conv1d_1[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 296, 128)  │        512 │ conv1d_2[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 298, 128)  │        512 │ conv1d_3[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 298, 128)  │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 297, 128)  │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 296, 128)  │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 298, 128)  │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 128)       │          0 │ dropout[0][0]     │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 128)       │          0 │ dropout[0][0]     │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 128)       │          0 │ dropout_1[0][0]   │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 128)       │          0 │ dropout_1[0][0]   │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 128)       │          0 │ dropout_2[0][0]   │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼─────────────────

 Total params: 4,201,331 (16.03 MB)

 Trainable params: 4,200,307 (16.02 MB)

 Non-trainable params: 1,024 (4.00 KB)

In [ ]:
modelCNN.fit(data, labels, validation_split=0.2,
            epochs=16, batch_size=128, callbacks=callbacks_list, shuffle=True)

Epoch 1/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 11s 272ms/step - accuracy: 0.4245 - loss: 11.2572 - val_accuracy: 0.0363 - val_loss: 2.4842
Epoch 2/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 259ms/step - accuracy: 0.5052 - loss: 2.1389 - val_accuracy: 0.0176 - val_loss: 2.4189
Epoch 3/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 260ms/step - accuracy: 0.5692 - loss: 1.9943 - val_accuracy: 0.0206 - val_loss: 2.4173
Epoch 4/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 259ms/step - accuracy: 0.6262 - loss: 1.8602 - val_accuracy: 0.0559 - val_loss: 2.3226
Epoch 5/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 259ms/step - accuracy: 0.6594 - loss: 1.7623 - val_accuracy: 0.0147 - val_loss: 2.3183
Epoch 6/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 259ms/step - accuracy: 0.6824 - loss: 1.6879 - val_accuracy: 0.0255 - val_loss: 2.3243
Epoch 7/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 262ms/step - accuracy: 0.7069 - loss: 1.6056 - val_accuracy: 0.0137 - val_loss: 2.6039
Epoch 8/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 8s 264ms/step - accuracy: 0.7637 - loss: 1.4771 - val_accuracy: 

In [ ]:
# Evaluate the model
loss, accuracy = modelCNN.evaluate(data, labels, verbose=0)

# Print the accuracy
print(f'Test Accuracy: {accuracy * 100:.2f}%')
print(f'Test Loss: {loss * 100:.2f}%')

Test Accuracy: 72.10%
Test Loss: 156.89%


#**LSTM**

In [ ]:
# Define input layer
inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

reshape = Reshape((sequence_length,EMBEDDING_DIM))(embedding)

# LSTM layers
lstm = LSTM(num_filters, return_sequences=True, kernel_regularizer=regularizers.l2(0.01))(reshape)
lstm = BatchNormalization()(lstm)
lstm = LSTM(num_filters, return_sequences=False, kernel_regularizer=regularizers.l2(0.01))(lstm)
lstm = BatchNormalization()(lstm)

# Fully connected layers
dropout = Dropout(drop)(lstm)
output = Dense(units=3, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(dropout)  # Ensure this matches the number of classes

# Create model
modelLSTM = Model(inputs, output)

# Optimizer with learning rate schedule
adam = Adam(learning_rate=0.001)

modelLSTM.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=4, verbose=1, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, verbose=1)

callbacks_list = [early_stopping, reduce_lr]

modelLSTM.summary()



Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 300)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (None, 300, 400)       │     3,167,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_3 (Reshape)             │ (None, 300, 400)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 300, 128)       │       270,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 300, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 128)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │           387 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,571,443 (13.62 MB)

 Trainable params: 3,570,931 (13.62 MB)

 Non-trainable params: 512 (2.00 KB)

In [ ]:
modelLSTM.fit(data, labels, validation_split=0.2,
              epochs=16, batch_size=128, callbacks=callbacks_list, shuffle=True)

Epoch 1/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 19s 554ms/step - accuracy: 0.4030 - loss: 8.0687 - val_accuracy: 0.0039 - val_loss: 6.9871 - learning_rate: 0.0010
Epoch 2/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 528ms/step - accuracy: 0.5761 - loss: 6.4792 - val_accuracy: 0.0029 - val_loss: 6.1926 - learning_rate: 0.0010
Epoch 3/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 527ms/step - accuracy: 0.6776 - loss: 5.3017 - val_accuracy: 0.0539 - val_loss: 5.3240 - learning_rate: 0.0010
Epoch 4/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 528ms/step - accuracy: 0.7632 - loss: 4.3168 - val_accuracy: 0.1569 - val_loss: 4.5814 - learning_rate: 0.0010
Epoch 5/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 527ms/step - accuracy: 0.8220 - loss: 3.5290 - val_accuracy: 0.1725 - val_loss: 3.9812 - learning_rate: 0.0010
Epoch 6/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 527ms/step - accuracy: 0.8690 - loss: 2.8864 - val_accuracy: 0.0275 - val_loss: 4.1489 - learning_rate: 0.0010
Epoch 7/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 17s 525ms/step - accuracy: 0.8938 - loss: 2.

In [ ]:
# Evaluate the model
loss, accuracy = modelLSTM.evaluate(data, labels, verbose=0)

# Print the accuracy
print(f'Test Accuracy: {accuracy * 100:.2f}%')
print(f'Test Loss: {loss * 100:.2f}%')

Test Accuracy: 72.02%
Test Loss: 253.31%



#**Combining CNN and LSTM**

In [ ]:
# Define your input layer
inputs = Input(shape=(sequence_length,))

# Embedding layer
embedding = Embedding(input_dim=vocab_size, output_dim=EMBEDDING_DIM, input_length=sequence_length)(inputs)

# CNN layers to extract features
conv_layers = []
for filter_size in filter_sizes:
    conv = Conv1D(num_filters, filter_size, activation='relu', kernel_regularizer=regularizers.l2(0.01))(embedding)
    conv = BatchNormalization()(conv)
    conv = Dropout(0.3)(conv)  # Increased dropout in convolutional layers
    conv = MaxPooling1D(sequence_length - filter_size + 1, strides=1)(conv)
    conv_layers.append(conv)

# Concatenate convolutional layers
merged_tensor = concatenate(conv_layers, axis=1)

# Reshape for LSTM input
reshape = Reshape((1, len(filter_sizes) * num_filters))(merged_tensor)

# Bidirectional LSTM layers
lstm = Bidirectional(LSTM(128, return_sequences=True, kernel_regularizer=regularizers.l2(0.01)))(reshape)
lstm = BatchNormalization()(lstm)
lstm = Dropout(0.3)(lstm)  # Increased dropout in LSTM layers

# Flatten the tensor
flatten = Flatten()(lstm)

# Dense layer with more units
dense = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.01))(flatten)
dropout_dense = Dropout(drop)(dense)

# Output layer
output = Dense(units=3, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(dropout_dense)

# Create the model
modelCNN_LSTM = Model(inputs, output)

# Compile the model with a smaller learning rate
adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
modelCNN_LSTM.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

# Model summary
modelCNN_LSTM.summary()

# Define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=6, verbose=1)
callbacks_list = [early_stopping]


Model: "functional_36"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_34      │ (None, 300)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_33        │ (None, 300, 400)  │  4,000,000 │ input_layer_34[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_94 (Conv1D)  │ (None, 298, 128)  │    153,728 │ embedding_33[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_95 (Conv1D)  │ (None, 297, 128)  │    204,928 │ embedding_33[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_96 (Conv1D)  │ (None, 296, 128)  │    256,128 │ embedding_33[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 298, 128)  │        512 │ conv1d_94[0][0]   │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 297, 128)  │        512 │ conv1d_95[0][0]   │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 296, 128)  │        512 │ conv1d_96[0][0]   │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_161         │ (None, 298, 128)  │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_162         │ (None, 297, 128)  │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_163         │ (None, 296, 128)  │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_39    │ (None, 1, 128)    │          0 │ dropout_161[0][0] │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_40    │ (None, 1, 128)    │          0 │ dropout_162[0][0] │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_41    │ (None, 1, 128)    │          0 │ dropout_163[0][0] │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_58      │ (None, 3, 128)    │          0 │ max_pooling1d_39… │
│ (Concatenate)       │                   │            │ max_pooling1d_40… │
│                     │                   │            │ max_pooling1d_41… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape_31          │ (None, 1, 384)    │          0 │ concatenate_58[0… │
│ (Reshape)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_67    │ (None, 1, 256)    │    525,312 │ reshape_31[0][0]  │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼─────────────────

 Total params: 5,209,219 (19.87 MB)

 Trainable params: 5,207,939 (19.87 MB)

 Non-trainable params: 1,280 (5.00 KB)

In [ ]:
# Training the model (Assuming 'data' and 'labels' are defined)
modelCNN_LSTM.fit(data, labels, validation_split=0.2,
                  epochs=16, batch_size=128, callbacks=callbacks_list, shuffle=True)


Epoch 1/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 11s 244ms/step - accuracy: 0.4099 - loss: 17.2481 - val_accuracy: 0.0000e+00 - val_loss: 13.5992
Epoch 2/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 231ms/step - accuracy: 0.6435 - loss: 12.0079 - val_accuracy: 0.0000e+00 - val_loss: 9.9725
Epoch 3/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 231ms/step - accuracy: 0.8310 - loss: 8.2494 - val_accuracy: 0.0000e+00 - val_loss: 7.6464
Epoch 4/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 230ms/step - accuracy: 0.9645 - loss: 5.6299 - val_accuracy: 0.0000e+00 - val_loss: 5.8801
Epoch 5/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 230ms/step - accuracy: 0.9711 - loss: 3.9731 - val_accuracy: 0.0000e+00 - val_loss: 4.7388
Epoch 6/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 230ms/step - accuracy: 0.9837 - loss: 2.8174 - val_accuracy: 0.0000e+00 - val_loss: 4.0061
Epoch 7/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 229ms/step - accuracy: 0.9835 - loss: 2.0274 - val_accuracy: 0.0000e+00 - val_loss: 3.5805
Epoch 8/16
32/32 ━━━━━━━━━━━━━━━━━━━━ 7s 230ms/step - accuracy: 0.9823 -

In [ ]:
# Evaluate the model
loss, accuracy = modelCNN_LSTM.evaluate(data, labels, verbose=0)

# Print the accuracy
print(f'Test Accuracy: {accuracy * 100:.2f}%')
print(f'Test Loss: {loss * 100:.2f}%')

Test Accuracy: 77.43%
Test Loss: 101.27%


#**BERT-based approach**

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub

In [ ]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

RuntimeError: Op type not registered 'CaseFoldUTF8' in binary running on DESKTOP-L1P2U0E. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib (e.g. `tf.contrib.resampler`), accessing should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

In [ ]:
# Training the model (Assuming 'data' and 'labels' are defined)
modelBert.fit(data, labels, validation_split=0.2,
                  epochs=1, batch_size=128, callbacks=callbacks_list, shuffle=True)


32/32 ━━━━━━━━━━━━━━━━━━━━ 102s 3s/step - accuracy: 0.4229 - loss: 1.0439 - val_accuracy: 0.0000e+00 - val_loss: 1.7886


In [ ]:
# Evaluate the model
loss, accuracy = modelBert.evaluate(data, labels, verbose=0)

# Print the accuracy
print(f'Test Accuracy: {accuracy * 100:.2f}%')
print(f'Test Loss: {loss * 100:.2f}%')

Test Accuracy: 33.33%
Test Loss: 118.46%


In [ ]:
# %reset -f

In [ ]:
print('Shape of X train and X validation tensor:',data.shape)
print('Shape of label train and validation tensor:', labels.shape)
print(data)
print(labels)

Shape of X train and X validation tensor: (5100, 300)
Shape of label train and validation tensor: (5100, 3)
[[   0    0    0 ... 4349    2  449]
 [   0    0    0 ...  480 4351   60]
 [   0    0    0 ...  680  124   23]
 ...
 [   0    0    0 ...  128   48   68]
 [   0    0    0 ...  569  128  335]
 [   0    0    0 ...   29  776  776]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [0 1 0]
 [0 1 0]
 [0 1 0]]


In [ ]:
import numpy as np
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification
from sklearn.model_selection import train_test_split

# Load the BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)
model.summary()
# Tokenize the reviews and create the attention mask
def tokenize_reviews(reviews, tokenizer, max_length=300):
    encodings = tokenizer(reviews, padding=True, truncation=True, max_length=max_length, return_tensors='tf')
    return encodings

train_encodings = tokenize_reviews(reviews_processed, tokenizer)

# Convert labels to integer format
labels_train = np.argmax(encoded_labels, axis=1)

# Prepare the inputs for the model, including 'input_ids' and 'attention_mask'
train_dataset = tf.data.Dataset.from_tensor_slices((
    {
        'input_ids': train_encodings['input_ids'],
        'attention_mask': train_encodings['attention_mask']
    },
    labels_train
)).shuffle(10000).batch(16)

# Define and compile the model
optimizer = Adam(learning_rate=0.00001)
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(train_dataset, epochs=3)

# Tokenize the test reviews
test_encodings = tokenize_reviews(data_test['Data'], tokenizer)

# Make predictions on the test set
predictions = model.predict(dict(test_encodings))
predicted_labels = np.argmax(predictions.logits, axis=1)

# Example output: predicted labels
print(predicted_labels)


All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Model: "tf_bert_for_sequence_classification_32"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
 dropout_1401 (Dropout)      multiple                  0 (unused)
                                                                 
 classifier (Dense)          multiple                  2307      
                                                                 
Total params: 109484547 (417.65 MB)
Trainable params: 109484547 (417.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


ValueError: Could not interpret optimizer identifier: <keras.src.optimizers.adam.Adam object at 0x000002199FFB8490>

In [ ]:
# Training the model
model.fit(data, labels, validation_split=0.2, epochs=16, batch_size=128, callbacks=callbacks_list, shuffle=True)